export const colors = {
  brand: {
    primary: "#2182BD",
    secondary: "#5282BD",
    muted: "#C6DAF7",
  },
  theme: {
    skyblue: "skyblue",
    lightbluewhite: "#E5ECE6",
  },
  ui: {
    primary: "#262626",
    secondary: "#757575",
    tertiary: "#F1F1F1",
    quaternary: "#FFFFFF",
    disabled: "#DEDEDE",
    error: "#D0421B",
    success: "#138000",
  },
  bg: {
    primary: "#FFFFFF",
    secondary: "#F1F1F1",
    fadeskyblue: "#73A4D670",
    grey: "grey",
    aqua: "#6bfff8",
    fadegreen: "#7BFF6B90",
    green: "green",
    ghee: "#efeaea",
    lightbluewhite: "#E5ECE6",
    blue: "blue",
    skyblue: "skyblue",
    white: "#ffff",
    red: "red",
    nextInput: "#3b81ca",
    purple: "#8C3573",
    black: "#000000",
    GraniteGray: "#60616A",
    yellow: "#ffff07",
    orange: "orange",
    pink: "#FF80BF",
    transparent: "transparent",
  },

  text: {
    primary: "#262626",
    secondary: "#757575",
    disabled: "#9C9C9C",
    inverse: "#FFFFFF",
    error: "#D0421B",
    success: "#138000",
    aqua: "#91E8EB",
    grey: "grey",
    blue: "blue",
    red: "red",
    white: "#ffff",
  },
};
