import { Sellings } from "./sell.items";

export const Properties = [
  {
    title: "Rent: Houses and Apartments",
    RenderItems: Sellings.sellApart,
    superCatogery: "houseapartment",
    icon: require("../../../../assets/subcatogery/rentapartment.png"),
    navigation: "home",
  },
  {
    title: "Sell: Houses and Apartments",
    RenderItems: Sellings.sellApart,
    superCatogery: "houseapartment",
    icon: require("../../../../assets/subcatogery/sellapartment.png"),
    navigation: "home",
  },
  {
    title: "Rent: Shopes and Offices",
    RenderItems: Sellings.rentshopoff,
    superCatogery: "shopeoffice",
    icon: require("../../../../assets/subcatogery/rentoffice.png"),
    navigation: "home",
  },
  {
    showPrice: "none",
    title: "Sell: Shopes and Offices",
    RenderItems: Sellings.sellshopoff,
    superCatogery: "shopeoffice",
    icon: require("../../../../assets/subcatogery/selloffice.png"),
    navigation: "home",
  },

  {
    title: "Rent: Land and Plot",
    RenderItems: Sellings.RentLand,
    superCatogery: "landplot",
    icon: require("../../../../assets/subcatogery/rentland.png"),
    navigation: "home",
  },

  {
    title: "Sell: Land and Plot",
    RenderItems: Sellings.RentLand,
    superCatogery: "landplot",
    icon: require("../../../../assets/subcatogery/sellland.png"),
    navigation: "home",
  },

  {
    title: "Paying Guest",
    RenderItems: Sellings.payingGuest,
    superCatogery: "payingguesthouse",
    icon: require("../../../../assets/subcatogery/pg.png"),
    navigation: "home",
  },

  {
    title: "Guest House",
    RenderItems: Sellings.payingGuest,
    superCatogery: "payingguesthouse",
    icon: require("../../../../assets/subcatogery/ghouse.png"),
    navigation: "home",
  },

  {
    title: "Roommate",
    RenderItems: Sellings.RoomMate,
    superCatogery: "roommate",
    icon: require("../../../../assets/subcatogery/roomate.png"),
    navigation: "home",
  },
];

export const Cars = [
  {
    title: "Cars",
    RenderItems: Sellings.sellCar,
    superCatogery: "carvehicle",
    icon: require("../../../../assets/subcatogery/cars.png"),
    navigation: "home",
  },
  {
    title: "Commercial & other Vehicles",
    RenderItems: Sellings.sellCar,
    superCatogery: "carvehicle",
    icon: require("../../../../assets/subcatogery/vehicle.png"),
    navigation: "home",
  },
  {
    title: "Spare Parts",
    RenderItems: Sellings.VehicleParts,
    superCatogery: "sphareparts",
    icon: require("../../../../assets/subcatogery/spare.png"),
    navigation: "home",
  },
];
export const Anything = [
  {
    title: "Sell Anything",
    superCatogery: "regular",
    to: "skip",
    icon: require("../../../../assets/subcatogery/viewall.png"),
    navigation: "home",
  },
];

export const Furniture = [
  {
    title: "Sofa",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/sofa.png"),
    navigation: "home",
  },
  {
    title: "Beds",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/bed.png"),
    navigation: "home",
  },
  {
    title: "Wardrobes",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/wardrobe.png"),
    navigation: "home",
  },
  {
    title: "Dining",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/dining.png"),
    navigation: "home",
  },
  {
    title: "Office Items",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/office.png"),
    navigation: "home",
  },
  {
    title: "Kitchen Items",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/kitchen.png"),
    navigation: "home",
  },
  {
    title: "Benches and Chairs",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/benchchair.png"),
    navigation: "home",
  },
  {
    title: "Home Decorations",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/homedecor.png"),
    navigation: "home",
  },
  {
    title: "Kids furniture",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/kidsfurniture.png"),
    navigation: "home",
  },
];

export const Jobs = [
  {
    title: "Teacher",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Driving",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "IT Technician & Developer",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Operator and Technician",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Data entry & Back office",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Receptionist & Front office",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Sales & Marketing",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Delivery & Collection",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "BPO & Marketing",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Cook",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Accountant",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Hotel and Travel",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Designer",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
  {
    title: "Other Jobs",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.Jobs,
    icon: "",
    navigation: "home",
  },
];

export const Kitchen = [
  {
    title: "Kitchenwares",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/Kitchenwares.png"),
    navigation: "home",
  },
  {
    title: "Microwaves",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/microwaves.png"),
    navigation: "home",
  },
  {
    title: "Steelwares",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/steelwares.png"),
    navigation: "home",
  },
  {
    title: "Ovens & Cookckers",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/ovencooker.png"),
    navigation: "home",
  },
  {
    title: "Electric Items",
    superCatogery: "jobs",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/fridge.png"),
    navigation: "home",
  },
  {
    title: "Foods",
    superCatogery: "jobs",
    to: "skip",
    icon: require("../../../../assets/subcatogery/foods.png"),
    navigation: "home",
  },
];

export const Computer = [
  {
    title: "PC",
    superCatogery: "pclaptop",
    RenderItems: Sellings.personalComputer,
    icon: require("../../../../assets/subcatogery/pc.png"),
    navigation: "home",
  },
  {
    title: "Laptops",
    superCatogery: "pclaptop",
    RenderItems: Sellings.LaptopSell,
    icon: require("../../../../assets/subcatogery/laptop.png"),
    navigation: "home",
  },
  {
    title: "Monitor",
    superCatogery: "monitor",
    to: "skip",
    RenderItems: Sellings.MonitorSell,
    icon: require("../../../../assets/subcatogery/monitor.png"),
    navigation: "home",
  },
  {
    title: "CPU",
    RenderItems: Sellings.CPU,
    superCatogery: "cpu",
    icon: require("../../../../assets/subcatogery/cpu.png"),
    navigation: "home",
  },
  {
    title: "Computer Parts and Assoceries",
    to: "skip",
    superCatogery: "regular",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/partsaccessories.png"),
    navigation: "home",
  },
  {
    title: "Keboard, Mouses and Speackers",
    to: "skip",
    superCatogery: "regular",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/keyboardmouse.png"),
    navigation: "home",
  },
];
export const Camera = [
  {
    title: "Camera Lenses",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/lense.png"),
    navigation: "home",
  },
  {
    title: "Compact Cameras",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/compactcamera.png"),
    navigation: "home",
  },
  {
    title: "DSLR Cameras",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/dslrcamera.png"),
    navigation: "home",
  },
  {
    title: "Mirrorless Cameras",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/mirrorlesscamera.png"),
    navigation: "home",
  },
  {
    title: "Action travel Cameras",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/gopro.png"),
    navigation: "home",
  },
  {
    title: "360 degree Cameras",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/camera360.png"),
    navigation: "home",
  },
  {
    title: "Traditional Cameras",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/oldcamera.png"),
    navigation: "home",
  },
];

export const TV = [
  {
    title: "LED, LCD, OLED & QLED TVs",
    to: "skip",
    superCatogery: "tvs",
    RenderItems: Sellings.TvDevice,
    icon: require("../../../../assets/subcatogery/ledandoled.png"),
    navigation: "home",
  },
  {
    title: "Subwoofer and Sound systems",
    to: "skip",
    superCatogery: "withbrand",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/soundaudio.png"),
    navigation: "home",
  },
  {
    title: "Old model Tvs",
    to: "skip",
    superCatogery: "withbrand",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/oldtvs.png"),
    navigation: "home",
  },
];
export const Mobile = [
  {
    title: "Mobiles",
    superCatogery: "mobiletablet",
    RenderItems: Sellings.Mobile,
    icon: require("../../../../assets/subcatogery/mobile.png"),
    navigation: "home",
  },
  {
    title: "Tablets & ipad",
    superCatogery: "mobiletablet",
    RenderItems: Sellings.Mobile,
    icon: require("../../../../assets/subcatogery/tabletandipad.png"),
    navigation: "home",
  },
  {
    title: "Accessories",
    to: "skip",
    superCatogery: "regular",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/mobileaccssories.png"),
    navigation: "home",
  },
];

export const Electronics = [
  {
    title: "Games & Entertainment",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/games.png"),
    navigation: "home",
  },
  {
    title: "Hard Disk, SSD and memory Drives",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.StorageDevice,
    icon: require("../../../../assets/subcatogery/harddisk.png"),
    navigation: "home",
  },
  {
    title: "Printers",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.Printers,
    icon: require("../../../../assets/subcatogery/printers.png"),
    navigation: "home",
  },
  {
    title: "Acs",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/acs.png"),
    navigation: "home",
  },
  {
    title: "Washing Machines",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/washingmachine.png"),
    navigation: "home",
  },
  {
    title: "Light & LEDS",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/light.png"),
    navigation: "home",
  },
];
export const Motorbike = [
  {
    title: "Motorcycle",
    superCatogery: "twowheeler",
    RenderItems: Sellings.Motorcycle,
    icon: require("../../../../assets/subcatogery/motorcycle.png"),
    navigation: "home",
  },
  {
    title: "Scooter",
    superCatogery: "twowheeler",
    RenderItems: Sellings.Motorcycle,
    icon: require("../../../../assets/subcatogery/Scooter.png"),
    navigation: "home",
  },
  {
    title: "Spare Parts",
    superCatogery: "sphareparts",
    RenderItems: Sellings.VehicleParts,
    icon: require("../../../../assets/subcatogery/spare.png"),
    navigation: "home",
  },
  {
    title: "Bicycle",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/bicycle.png"),
    navigation: "home",
  },
];

export const Books = [
  {
    title: "School books",
    superCatogery: "books",
    to: "skip",
    // RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Collage Books",
    superCatogery: "books",
    to: "skip",
    // RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Action and Adventure",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Classics",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Comic Book or Graphic Novel",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Biographies and Autobiographies",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Detective and Mystery",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Fantasy",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Historical Fiction",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Horror",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Literary Fiction",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Romance",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Science Fiction (Sci-Fi)",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Short Stories",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Suspense and Thrillers",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Women's Fiction",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Cookbooks",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Essays",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "History",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Memoir",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Poetry",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
  {
    title: "Self-Help",
    superCatogery: "books",
    to: "skip",
    RenderItems: Sellings.Books,
    icon: "",
    navigation: "home",
  },
];

export const Sports = [
  {
    title: "Gym & Fitness",
    to: "skip",
    superCatogery: "regular",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/fitness.png"),
    navigation: "home",
  },
  {
    title: "Musical Instrument",
    superCatogery: "withbrand",
    to: "skip",
    RenderItems: Sellings.withBrand,
    icon: require("../../../../assets/subcatogery/musicalinstrument.png"),
    navigation: "home",
  },
  {
    title: "Sports Instruments",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/sportsinstrument.png"),
    navigation: "home",
  },
  {
    title: "Other Hobbies",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.UsedThings,
    icon: require("../../../../assets/subcatogery/otherhobbies.png"),
    navigation: "home",
  },
];

export const Fashion = [
  {
    title: "Men",
    superCatogery: "cloths",
    to: "skip",
    RenderItems: Sellings.Fashion,
    icon: require("../../../../assets/subcatogery/menclothes.png"),
    navigation: "home",
  },
  {
    title: "Women",
    superCatogery: "cloths",
    to: "skip",
    RenderItems: Sellings.Fashion,
    icon: require("../../../../assets/subcatogery/womenclothes.png"),
    navigation: "home",
  },
  {
    title: "Kids",
    superCatogery: "cloths",
    to: "skip",
    RenderItems: Sellings.Fashion,
    icon: require("../../../../assets/subcatogery/kidsclothes.png"),
    navigation: "home",
  },
];
export const Pets = [
  {
    title: "Dogs",
    superCatogery: "pets",
    to: "skip",
    RenderItems: Sellings.AnimalPet,
    icon: require("../../../../assets/subcatogery/dog.png"),
    navigation: "home",
  },
  {
    title: "Aquarium & Decoration",
    superCatogery: "regular",
    to: "skip",
    RenderItems: Sellings.Aquarium,
    icon: require("../../../../assets/subcatogery/Aquarium.png"),
    navigation: "home",
  },
  {
    title: "food & Accessories",
    superCatogery: "pets",
    to: "skip",
    RenderItems: Sellings.none,
    icon: require("../../../../assets/subcatogery/petfood.png"),
    navigation: "home",
  },
  {
    title: "Other Pets",
    superCatogery: "pets",
    to: "skip",
    RenderItems: Sellings.AnimalPet,
    icon: require("../../../../assets/subcatogery/otherpets.png"),
    navigation: "home",
  },
];
export const Service = [
  {
    title: "Computer Software and Hardware",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/pc.png"),
    navigation: "home",
  },
  {
    title: "Mechanical & Maintenance",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/mechanical.png"),
    navigation: "home",
  },
  {
    title: "Electronics",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/electronics.png"),
    navigation: "home",
  },
  {
    title: "Education and Classes",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/teacher.png"),
    navigation: "home",
  },
  {
    title: "Drivers & taxi",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/driving.png"),
    navigation: "home",
  },
  {
    title: "Helthcare",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/helthcare.png"),
    navigation: "home",
  },
  {
    title: "Parlor and Beauty",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/beauty.png"),
    navigation: "home",
  },
  {
    title: "Other Services",
    to: "skip",
    RenderItems: Sellings.none,
    superCatogery: "regular",
    icon: require("../../../../assets/subcatogery/services.png"),
    navigation: "home",
  },
];
