import {
  Properties,
  Cars,
  Furniture,
  Jobs,
  Kitchen,
  Computer,
  Camera,
  TV,
  Mobile,
  Electronics,
  Motorbike,
  Books,
  Sports,
  Fashion,
  Pets,
  Service,
  SellingProperties,
  SellingCars,
  SellingFurniture,
  SellingJobs,
  SellingKitchen,
  SellingComputer,
  SellingCamera,
  SellingTV,
  SellingMobile,
  SellingElectronics,
  SellingMotorbike,
  SellingBooks,
  SellingSports,
  SellingFashion,
  SellingPets,
  SellingService,
  Anything,
} from "./component.details";

export const SecondCato = [
  // {
  //   title: "Properties",
  //   icon: "apartment",
  //   navigate: "second-catogery",
  //   source: "material",
  //   payload: Properties,
  //   mapCat: "Properties",
  // },
  {
    title: "Anything",
    navigate: "important-info",
    img: require("../../../../assets/catogery/anything.svg").default,
    payload: Anything,
    mapCat: "Properties",
  },
  {
    title: "Mobile and Tablets",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/phone.svg").default,
    payload: Mobile,
    // payloadSell: SellingMobile,
    mapCat: "Mobile Tablets",
  },

  {
    title: "Computers and Laptops",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/desktop.svg").default,
    payload: Computer,
    // payloadSell: SellingComputer,
    mapCat: "Computer Laptop",
  },
  {
    title: "Electronics and Appliences",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/electric.svg").default,
    payload: Electronics,
    // payloadSell: SellingElectronics,
    mapCat: "Electronics",
  },
  {
    title: "TV video and Audio",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/tv.svg").default,
    payload: TV,
    // payloadSell: SellingTV,
    mapCat: "Tvs",
  },
  {
    title: "Furniture",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/furniture.svg").default,
    payload: Furniture,
    // payloadSell: SellingFurniture,
    mapCat: "Furniture",
  },
  // {
  //   title: "Jobs",
  //   icon: "work-outline",
  //   navigate: "second-catogery",
  //   source: "material",
  //   payload: Jobs,
  // payloadSell: SellingJobs,
  //   mapCat: "Jobs",
  // },
  {
    title: "Kitchen Appliances",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/kitchen.svg").default,
    payload: Kitchen,
    // payloadSell: SellingKitchen,
    mapCat: "Kitchen Appliances",
  },

  {
    title: "Camera And Lenses",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/camera.svg").default,
    payload: Camera,
    // payloadSell: SellingCamera,
    mapCat: "Camera And Lenses",
  },

  {
    title: "Books",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/book.svg").default,
    payload: Books,
    // payloadSell: SellingBooks,
    mapCat: "Books",
  },
  {
    title: "Cars",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/car.svg").default,
    payload: Cars,
    // payloadSell: SellingCars,
    mapCat: "Cars",
  },

  {
    title: "Motorbike and Bikes",
    navigate: "second-catogery",
    img: require("../../../../assets/catogery/bikes.svg").default,
    payload: Motorbike,
    // payloadSell: SellingMotorbike,
    mapCat: "Motorbikes & bikes",
  },
  // {
  //   title: "Sports & Hobbies",
  //   icon: "sports-soccer",
  //   navigate: "second-catogery",
  //   source: "material",
  //   payload: Sports,
  // payloadSell: SellingSports,
  //   mapCat: "Sports & Hobbies",
  // },
  // {
  //   title: "Fashion",
  //   icon: "mobile",
  //   navigate: "second-catogery",
  //   source: "font-awesome",
  //   payload: Fashion,
  // payloadSell: SellingFashion,
  //   mapCat: "Fashion",
  // },
  // {
  //   title: "Pets",
  //   icon: "paw",
  //   navigate: "second-catogery",
  //   source: "font-awesome",
  //   payload: Pets,
  // payloadSell: SellingPets,
  //   mapCat: "Pets",
  // },
  // {
  //   title: "Services",
  //   icon: "handshake-o",
  //   navigate: "second-catogery",
  //   source: "font-awesome",
  //   payload: Service,
  // payloadSell: SellingService,
  //   mapCat: "Services",
  // },
];
